apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yxjenoy6o-go 
  janus-idp.io/tekton: yxjenoy6o-go
  backstage.io/kubernetes-id: yxjenoy6o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yxjenoy6o-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml