apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yxjenoy6o-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yxjenoy6o-go 
  name: yxjenoy6o-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yxjenoy6o-go 
